site_name: Zero to Mastery Machine Learning
site_author: thangckt
# site_url: https://www.learnpytorch.io
site_description:  Zero to Mastery Machine Learning Course on Udemy
docs_dir: "docs/"

# repo_url: https://github.com/mrdbourke/pytorch-deep-learning/
# repo_name: mrdbourke/pytorch_deep_learning
# edit_uri: ""

## Copyright
copyright: Copyright &copy; 2022 <a href="https://thangckt.github.io">thangckt</a>

## Configuration
theme:
  name: "material"     #  "material"    "mkdocs"    "readthedocs"     'rtd-dropdown'   windmill  bootswatch
  # logo: assets/ztm-logo-and-pytorch-logo.png
  # favicon: assets/ztm-logo-and-pytorch-logo.png

  highlightjs: true
  features:
    - content.code.annotate
    # - navigation.expand
    # - navigation.sections
    - navigation.indexes
    # - navigation.instant
    - navigation.tracking
    - navigation.top
    - search.suggest
    - toc.follow
    # - toc.integrate
    # - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.tabs.header   # only in extended theme
    ### new in v9
    - content.action.edit
    - navigation.footer


  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      # primary: blue grey   #  blue grey, indigo
      # accent: indigo
      toggle:
        icon: material/eye
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      # primary: blue grey   #  blue grey, indigo
      # accent: indigo
      toggle:
        icon: material/eye-outline
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono


## Customization
extra:
  generator: false
  analytics:
    provider: google
    property: G-QM7DWGY7ZT
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:<thanckt@gmail.com>
      name: Email to thangckt
    - icon: fontawesome/brands/telegram
      link: https://t.me/thangckt
      name: thangckt on Telegram
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/thangckt5
      name: thangckt on Facebook
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/thangckt
      name: thangckt on Linkedin
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/0000-0001-9826-5397
      name: thangckt on ORCID

## Extensions
markdown_extensions:
  - admonition
  - meta
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

## Plugins
plugins:
  - mkdocs-jupyter:
      include_source: True
      # theme: dark
  - search
  - social

### Extra theme
extra_javascript:
  - _extend_theme/javascripts/gg_adsense.js
extra_css:
  - _extend_theme/extra_css/full_width.css
  - _extend_theme/extra_css/font_size.css




###=======================================
### Site content
###=======================================
## Page tree
nav:
  - Home: README.md
  - 1. Getting Ready for ML:
    - A 6-step Framework: section-1-getting-ready-for-machine-learning/a-6-step-framework-for-approaching-machine-learning-projects.md
  - 2. Data Science and ML tools: 'section-2-data-science-and-ml-tools/README.md'
    - Introduction to Numpy: section-2-data-science-and-ml-tools/introduction-to-numpy.ipynb
    - Introduction to Pandas: section-2-data-science-and-ml-tools/introduction-to-pandas.ipynb


